/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./providers/**/*.{js,jsx,ts,tsx}",
    "./styles/**/*.{js,jsx,ts,tsx}",
    "./utils/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        // RN은 weight 매핑이 자동이 아님 → 각 weight를 개별 family로
        binggrae: ["binggrae"],
        "binggrae-bold": ["binggrae-bold"],
      },
      fontSize: {
        h1: [28, { lineHeight: 34 }],
        h2: [26, { lineHeight: 32 }],
        h3: [24, { lineHeight: 30 }],
        h4: [20, { lineHeight: 26 }],
        h5: [18, { lineHeight: 24 }],
        "3xl": [28, { lineHeight: 34 }],
        "2xl": [26, { lineHeight: 32 }],
        xl: [22, { lineHeight: 28 }],
        lg: [20, { lineHeight: 26 }],
        base: [18, { lineHeight: 24 }],
        md: [16, { lineHeight: 22 }],
        sm: [14, { lineHeight: 20 }],
        xs: [12, { lineHeight: 18 }],
        "2xs": [10, { lineHeight: 16 }],
      },
      colors: {
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
        },
        neutral: {
          50: "var(--color-neutral-50)",
          100: "var(--color-neutral-100)",
          200: "var(--color-neutral-200)",
          300: "var(--color-neutral-300)",
          400: "var(--color-neutral-400)",
          500: "var(--color-neutral-500)",
          600: "var(--color-neutral-600)",
        },
        danger: {
          20: "var(--color-danger-20)",
          50: "var(--color-danger-50)",
          100: "var(--color-danger-100)",
          200: "var(--color-danger-200)",
          300: "var(--color-danger-300)",
          400: "var(--color-danger-400)",
          500: "var(--color-danger-500)",
          600: "var(--color-danger-600)",
        },
        white: "var(--color-white)",
        black: "var(--color-black)",
        background: "var(--color-background)",
      },
    },
  },
  plugins: [],
};
